### PR TITLE
Update Form elements to use local state

### PR DESCRIPTION
**Pull request by asimonok**
Update Form elements to use local state.

### CODE REVIEW

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Comment by Yoslandy** [comment]
Hi @mikhail-vl 
Im not sure if this is the correct place and if this update has something to do with my issue.

I have been using and testing Data Manipulation plugin for my company which handle several Customer as automatization.
I have a dashboard on Grafana Cloud where the plugin was working smooth and nice created around 4 months ago. Now my company wants to implement the plugin in all customers to introduce data. But after install it in a new grafana instance I have a problem trying to access to the updated/new values.
The only difference I can see is that in my old dashboard the plugin is 2.7.0 and after install it yesterday in the new instance is version 3.0.0. I was trying to downgrade but I think I cant.

I was using this code in Update function the get the values options.elements[0].value  but now its not giving me the new value.

I wondering if something change and if this post has something to do with it. Trying to get some example code but Im not getting through.

Could you help me please, its is very important for us right now.

Thanks in advance

**Comment by mikhail-vl** [comment]
@Yoslandy Data Manipulation v3 has breaking changes in the way how we handle values. Values are stored in the local state instead of options.

  You can get values using just elements:

```
elements.forEach((element) => {
  console.log( element.id + '= ' + element.value );
})
```

  Let me know if it helps.

**Comment by mikhail-vl** [comment]
@Yoslandy You are very welcome and we appreciate the support.

  Let us know if there is anything else.

**Comment by Yoslandy** [comment]
@mikhail-vl Sorry for disturb you again

options.elements.forEach((element, index) => {
  element.value = ""
})
onOptionsChange(elements)

this is to restart values. Should be something like this but dont work

elements.forEach((element, index) => {
  element.value = ""
})
onChange(elements)

Any idea. any documentation updated that I can check

Sorry and thanks

**Comment by mikhail-vl** [comment]
@Yoslandy Let me test it.

**Comment by mikhail-vl** [comment]
@Yoslandy I don't think you need to call `onChange` any more, as values are stored in the local state.

  I just tested and it works for me. Let me know.

```
elements.forEach((element, index) => {
  element.value = ""
})
```

@asimonok Could you please confirm that it's the correct approach or we should expose additional methods to update elements?

**Comment by asimonok** [comment]
@mikhail-vl Updating local elements instead of dashboard options can be a reasonable so I've added onChange function for custom code in #214

@Yoslandy mutable updates can cause unexpected behavior so immutable updates are preferable because it will work more stable.

This example may work for you:
```
onOptionsChange({
  ...options,
  elements: options.elements.map((element) => {
    return {
       ...element,
       value: '',
     }
    })
});
```

Read more about immutable updates of arrays - https://react.dev/learn/updating-arrays-in-state#updating-arrays-without-mutation

**Comment by Yoslandy** [comment]
Hi @mikhail-vl and @asimonok 
I appreciate a lot your help

Just as an update. Since I receive your update I have been trying both ways and trying to fit some specification by my own but at this point I think I need your help again.

As I said, both option work good, but the first one dont update the panel, even when it filling the values.
Second option (@asimonok ) seems to be working better, even when I dont know If Im using it correctly. Will show you

This is part of my dashboard. Left panel is just to update database and is reflect it in right panel (this step is working good after the update with the code below)
image

This is the main piece of code as initial state in right panel.
...
`
          const body = json.body;
          //Fill The Dropdown
          newOptionsArray = [];
          body.forEach((element) => {
            newOptionsArray.push({ value: element.id, label: element.name });
          });
          elements[4].options = newOptionsArray;

          //From another fetch above
          const pallet_weight = body_json.palletWeight;
          const crate_weight = body_json.crateWeight;

          const elements_array = [pallet_weight, crate_weight, 0, 1, newOptionsArray[0].value, "live", "us", "n_msc"];
          onOptionsChange({
            ...options,
            elements: options.elements.map((element, index) => {
              return {
                ...element,
                value: elements_array[index],
              };
            }),
          `
          ...
          
          In this way I got to update the form with default values, and positioning the dropdown and the select field. But the dropdown is dynamically and in the time I cant update it with the new values which are in newOptionsArray.
          I use to do it so in the old version. 
          `options.elements[4].options = newOptionsArray;`
          
          Now is updated but dont be reflected in the form.
          
          Could you tell me if the is another better way to restart and fulfil the fields, or if Im correct (at least works)
          And please, how to dynamically populate the dropdown this time
          
          I did try many thing to not bother you but...
          
          Thanks in advance

**Comment by Yoslandy** [comment]
Hi again @mikhail-vl and @asimonok 

I figured out how to solve the problem. Here is the code of how I fix it. Maybe will be useful for somebody else.

```
const elements_array = [pallet_weight, crate_weight, 0, 1, "", "live", "us", "n_msc"];
onOptionsChange({
  ...options,
  elements: options.elements.map((element, index) => {
    console.log(element)
    if (index == 4) {
      return {
        ...element,
        options: newOptionsArray,
        value: newOptionsArray[0].value,
      };
    } else {
      return {
        ...element,
        value: elements_array[index],
      };
    }
  }),
});
```

Thanks again

**Comment by mikhail-vl** [comment]
@Yoslandy, glad you figured it out. We can't test all use cases when releasing a new version because we don't know how the community uses them. We try to keep breaking changes to a minimum and always mention them in the CHANGELOG.

  We added the `onChange` method similar to `onOptionsChange`, which updates the local state instead of updating the dashboard in the upcoming version v3.1.0.
  
  Let us know if there is anything else.

**Comment by Yoslandy** [comment]
Thanks @mikhail-vl you are doing a great, don't worry. I cant wait to see the new version.

Just if its possible, as an tip. I always look at the documentation and all about in internet to get something done before ask. Therefore a documentation updated will be great, I read about the changes on 3.0.0 but didn't see examples to have an idea, for example.

We are planning to use other plugins that we find useful from you. A good documentation always help

Thanks again for everything. Dashboards are working great now. 💯

**Comment by mikhail-vl** [comment]
@Yoslandy Thank you. All our plugins have YouTube tutorials and documentation to cover the main features.

  Let us know in the comments or open an issue if you have any questions.

**Pull request merged**
