### PR TITLE
Add Link Element

### LINKED ISSUE #286: Add TextLink form element
It's currently not possible to display a clickable link
Would be very nice to have it
https://github.com/grafana/grafana/tree/main/packages/grafana-ui/src/components/Link

And in general, is it possible to just support the use of any element from the [grafana-ui](https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-intro--page) in a smart dynamic way?

### PR DESCRIPTION
**Pull request by asimonok**
Resolves #286

### CODE REVIEW

**Review by mikhail-vl — APPROVED** [review]
Looks great!

**Comment by tomikos** [comment]
Thank you!
Unfortunately i get the following error
Screenshot 2023-11-25 at 17 02 43
I also tried to read the link via the Query Field or to put https://github.com in the Link Text - both failed

Grafana v10.0.3

**Comment by mikhail-vl** [comment]
@tomikos Interesting, we did development on 10.2.1. I will check the 10.0.3 and get back to you.

**Comment by tomikos** [comment]
any update on this?

**Comment by mikhail-vl** [comment]
@tomikos We used `TextLink` component from `@grafana/ui` for Link, which was introduced in Grafana 10.1.0.

  Unfortunately, It's not supported in Grafana 10.0.3. Please update to the 10.1.0 or the latest release, which fixed multiple security issues since 10.0.3.

  Thank you for reporting, we updated documentation accordingly.

**Pull request merged**
