### PR TITLE
Added custom color/background color for elements

### PR DESCRIPTION
**Pull request by vitPinchuk**
Resolves: #373 
Allow add background color for element/label;  
Allow add color for label;

### CODE REVIEW

**Review by asimonok — CHANGES_REQUESTED** [review]
Please replace with ColorPicker and add a clear button

**Comment by vitPinchuk** [comment]
@asimonok I added ColorPicker and a clear buttons

**Review by asimonok — APPROVED** [review]
Looks good!

@mikhail-vl ready for review

**Review by mikhail-vl — APPROVED** [review]
Looks great!

**Pull request merged**
