### PR TITLE
Add File element type for File Upload

### LINKED ISSUE #122: Files upload
Hi,

I have a requirement to submit the Textarea along with user uploaded files. Is there a way to upload files and send to API?

### PR DESCRIPTION
**Pull request by asimonok**
Resolves #122 

Screenshot 2023-08-18 at 10 59 19

### CODE REVIEW

**Review by mikhail-vl — APPROVED** [review]
Looks great!

**Comment by utkarshsalunkhe** [comment]
Please let me know how to use this file upload in my panel. Provide step-by-step instructions .

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe It's going to be in the release now.

  If you want to the the CI Artifact, then just download, install and add the element File to the form.

**Comment by utkarshsalunkhe** [comment]
@mikhail-vl   "After uploading a file from my local system to an API, what will the API send in response? Is it the path of the file? I want to send the path of the file to the backend." Is that correct?

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe The panel will send the file itself as Base64 if selected `application/json` type or as a binary in case of the form-data.

**Comment by mikhail-vl** [comment]
@vanimesh We appreciate the interest and we will add examples in the relevant issues.

**Pull request merged**
