### PR TITLE
Add Hidden option to String element

### PR DESCRIPTION
**Pull request by githubDante**
Added Hidden String Input to the Type selection for which I asked in #170 :)

### CODE REVIEW

**Comment by mikhail-vl** [comment]
@githubDante Thank you. I will review and test later today.

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Comment by mikhail-vl** [comment]
@githubDante Thank you for your contribution. I looked at it and instead of introducing the hidden element I decided to add add hidden option to the String element.

  I hope it works for you.

**Comment by mikhail-vl** [comment]
You are welcome to test and use the CI build if you need it before the official release next week: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/runs/4847844160.

**Comment by mikhail-vl** [comment]
Resolves #170.

**Comment by githubDante** [comment]
> You are welcome to test and use the CI build if you need it before the official release next week: https://github.com/VolkovLabs/volkovlabs-form-panel/actions/runs/4847844160.

Looks nice and it works as expected. Thank you!

**Comment by mikhail-vl** [comment]
@githubDante Thank you for confirming.

**Pull request merged**
