### PR TITLE
Added input type time

### PR DESCRIPTION
**Pull request by vitPinchuk**
Resolves: #351

### CODE REVIEW

**Review by asimonok — CHANGES_REQUESTED** [review]
Standard input looks good but it differs from the another inputs (from grafana/ui). To keep all controls are consistent, please use https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-timepickers-timeofdaypicker--basic&args=value:!date(2024-04-10T13:57:04.095Z)

**Comment by vitPinchuk** [comment]
> Standard input looks good but it differs from the another inputs (from grafana/ui). To keep all controls are consistent, please use https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-timepickers-timeofdaypicker--basic&args=value:!date(2024-04-10T13:57:04.095Z)

Added TimeOfDayPicker. But he works with value in format "2024-04-11T11:18:48.486Z" instead of the standard input that returns and accepts a string of the type "12:30"

**Review by asimonok — APPROVED** [review]
Looks good!

@mikhail-vl ready for review

**Review by mikhail-vl — APPROVED** [review]
Looks good!

**Pull request merged**
